---
version: "3.7"
services:
    ui:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./UI:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: mbtech
            MYSQL_USER: marlin
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        secrets:
            - db_password
            - db_root_password
        volumes:
            - ./DB_Dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: marlin
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        secrets:
            - db_password
            - db_root_password
secrets:
   db_password:
     file: .secrets/db_password.txt
   db_root_password:
     file: .secrets/db_root_password.txt
volumes:
    persistent:

